version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bewise_t
      POSTGRES_PASSWORD: bewise_t
      POSTGRES_DB: bewise_t
    volumes:
      - ./postgres-data:/var/lib/bewise_t/data
  
  fastapi:
    build: ./
    ports:
      - "8000:8000"  
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://bewise_t:bewise_t@postgres:5432/bewise_t